<?php return array (
  'amilibia\\amilibia\\Plugin' => 'plugins/amilibia/amilibia/Plugin.php',
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'rainlab\\translate\\Plugin' => 'plugins/rainlab/translate/Plugin.php',
  'rainlab\\builder\\Plugin' => 'plugins/rainlab/builder/Plugin.php',
  'rainlab\\pages\\Plugin' => 'plugins/rainlab/pages/Plugin.php',
  'system\\Controllers\\updates' => 'modules/system/controllers/updates.php',
  'RainLab\\Translate\\Models\\Locale' => 'plugins/rainlab/translate/models/Locale.php',
  'RainLab\\Translate\\Classes\\Translator' => 'plugins/rainlab/translate/classes/Translator.php',
  'Amilibia\\Amilibia\\Api\\Products' => 'plugins/amilibia/amilibia/api/Products.php',
  'Amilibia\\Amilibia\\Models\\Product' => 'plugins/amilibia/amilibia/models/Product.php',
  'RainLab\\Translate\\Classes\\TranslatableBehavior' => 'plugins/rainlab/translate/classes/TranslatableBehavior.php',
  'RainLab\\Translate\\Behaviors\\TranslatableModel' => 'plugins/rainlab/translate/behaviors/TranslatableModel.php',
  'Amilibia\\Amilibia\\Api\\Works' => 'plugins/amilibia/amilibia/api/Works.php',
  'Amilibia\\Amilibia\\Models\\Work' => 'plugins/amilibia/amilibia/models/Work.php',
  'Amilibia\\Amilibia\\Api\\Pages' => 'plugins/amilibia/amilibia/api/Pages.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins/rainlab/pages/classes/Router.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins/rainlab/pages/classes/PageList.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins/rainlab/pages/classes/Page.php',
  'RainLab\\Translate\\Behaviors\\TranslatablePageUrl' => 'plugins/rainlab/translate/behaviors/TranslatablePageUrl.php',
  'RainLab\\Translate\\Behaviors\\TranslatableCmsObject' => 'plugins/rainlab/translate/behaviors/TranslatableCmsObject.php',
);